### PR TITLE
#67 Install APK file

### PR DESCRIPTION
**Pull request by jo-elimuai**

### CODE REVIEW

**Comment by jo-elimuai** [comment]
screenshot_20171001-182409

screenshot_20171001-182415

**Comment by jo-elimuai** [comment]
screenshot_20171001-183502

**Comment by sladomic** [comment]
@jo-elimuai I have the same behaviour. Launcher is installed, but Shapi not. However I don't think, that the app store detects the launcher as being installed (I see the Download button again).

Also all version numbers are set to null

I cannot use the launcher (if I click on the home button I don't get a prompt to change the launcher)

**Comment by jo-elimuai** [comment]
> However I don't think, that the app store detects the launcher as being installed (I see the Download button again).

@sladomic Good observation. I'm fixing this now.

**Comment by jo-elimuai** [comment]
screenshot_20171001-195702

**Comment by jo-elimuai** [comment]
screenshot_20171001-201025

**Pull request merged**
